# workflow.yaml - 统一工作流配置文件
# 包含报告生成、评价和改进的所有角色配置

service_providers:
  ollama:
    base_url: "http://localhost:11434"
    default_model: "deepseek-r1:32b"
  qwen:
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    default_model: "qwen3-0.6b"
    api_key: "your_api_key_here"

roles:
  # ======================= 报告生成角色 =======================
  
  # 结论提出者
  conclusion_generator:
    name: "结论提出者"
    description: "负责分析数据并生成核心结论"
    system_prompt: "You are a Strategic Analyst. Synthesize concise, evidence-based conclusions for analytical reports. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      You are a Strategic Analyst. Synthesize a concise, evidence-based conclusion for the report on:
      "{question}"
      ### Data Summary
      Background: {background}
      Statistics: {statistics}
      Challenges: {challenges}
      Expert Views: {expert_opinions}
      Instructions:
      - Write 1–2 sentences that capture the essence of the report
      - Balance progress and challenges (avoid being overly positive or negative)
      - Do NOT repeat facts — interpret them to form an insightful conclusion
      - This conclusion will guide all subsequent writing
      - Output ONLY PLAIN TEXT with no formatting
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final conclusion content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      Output ONLY the conclusion (no explanations, no quotes, no markdown, no thinking process):
    temperature: 0.3
    max_tokens: 200
    timeout: 30

  # 政策分析师
  policy_analyst:
    name: "政策分析师"
    description: "专注于政策与监管框架分析"
    system_prompt: "You are a Policy Analyst specializing in regulatory frameworks and government policies. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      Report Topic: {question}
      Core Conclusion: "{conclusion}"
      Previous sections: {context}
      
      Your Task: Write the "Policy & Regulatory Framework" section (150–180 words).
      Data: {background_facts}
      
      Instructions:
      - Explain how national plans, regulations, and standards drive development
      - Link to the core conclusion
      - Cite sources naturally
      - Do NOT use markdown or headings
      - Output ONLY PLAIN TEXT with no formatting
      - Output only your new content (no repetition)
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final policy analysis content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      New content:
    temperature: 0.4
    max_tokens: 250
    timeout: 40
    top_p: 0.9

  # 市场研究员
  market_researcher:
    name: "市场研究员"
    description: "分析市场趋势和采用情况"
    system_prompt: "You are a Market Research Analyst specializing in technology adoption and market trends. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      Report Topic: {question}
      Core Conclusion: "{conclusion}"
      Previous sections: {context}
      
      Your Task: Write the "Market Adoption & Trends" section (150–180 words).
      Data: {statistics}
      
      Instructions:
      - Highlight market size, sector penetration, innovation metrics
      - Interpret what data implies about momentum or barriers
      - Connect to conclusion
      - No markdown, no headings
      - Output ONLY PLAIN TEXT with no formatting
      - Output only new content
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final market analysis content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      New content:
    temperature: 0.4
    max_tokens: 250
    timeout: 40

  # 案例专家
  case_specialist:
    name: "案例专家"
    description: "整理和分析实际应用案例"
    system_prompt: "You are a Case Study Specialist focusing on real-world implementation examples. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      Report Topic: {question}
      Core Conclusion: "{conclusion}"
      Previous sections: {context}
      
      Your Task: Write the "Implementation Cases" section (180–220 words).
      Cases: {case_studies}
      
      Instructions:
      - Describe 2–3 cases with narrative flow
      - Emphasize impact and methodology
      - Show how they validate or challenge the conclusion
      - No markdown
      - Output ONLY PLAIN TEXT with no formatting
      - Output only new content
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final case study content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      New content:
    temperature: 0.4
    max_tokens: 300
    timeout: 45

  # 技术解释者
  technical_interpreter:
    name: "技术解释者"
    description: "解释技术原理和权衡"
    system_prompt: "You are a Technical Specialist explaining complex technical concepts clearly. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      Report Topic: {question}
      Core Conclusion: "{conclusion}"
      Previous sections: {context}
      
      Your Task: Write the "Technical Foundations" section (120–150 words).
      Key Info:
      - Methods: {methods}
      - Accuracy metrics: {accuracy_metrics}
      
      Instructions:
      - Explain technical methods briefly
      - Discuss performance vs. interpretability trade-off
      - Link to conclusion
      - No markdown
      - Output ONLY PLAIN TEXT with no formatting
      - Output only new content
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final technical content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      New content:
    temperature: 0.3
    max_tokens: 200
    timeout: 35

  # 社会观察员
  societal_observer:
    name: "社会观察员"
    description: "分析社会接受度和文化影响"
    system_prompt: "You are a Social Impact Analyst examining societal acceptance and cultural factors. CRITICAL: Output ONLY the final result in Chinese, with NO thinking过程, planning, or reasoning steps."
    prompt_template: |
      Report Topic: {question}
      Core Conclusion: "{conclusion}"
      Previous sections: {context}
      
      Your Task: Write the "Social Acceptance" section (100–130 words).
      Key Challenge: {social_challenges}
      
      Instructions:
      - Discuss trust, human judgment, domain-specific resistance
      - Link to conclusion
      - No markdown
      - Output ONLY PLAIN TEXT with no formatting
      - Output only new content
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final social analysis content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      New content:
    temperature: 0.4
    max_tokens: 150
    timeout: 30

  # ======================= 通用角色 =======================
  
  # 简单聊天角色 - 用于通用对话
  simple_chat:
    name: "简单聊天助手"
    description: "用于通用对话和简单任务的聊天助手"
    system_prompt: "You are a helpful AI assistant capable of answering questions and performing simple tasks. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: "{question}"
    temperature: 0.7
    max_tokens: 500
    timeout: 30
  
  # ======================= 评价和改进角色 =======================
  
  # 严厉评价师 - 对报告进行多维度严厉评价
  report_evaluator:
    name: "严厉评价师"
    description: "对报告进行严厉的多维度质量评价"
    system_prompt: "You are a Distinguished Academic Quality Assessor with exceptionally high standards for analytical reports. Your role is to conduct rigorous, comprehensive evaluations of report quality across multiple dimensions. You maintain the highest academic standards and provide detailed, actionable feedback. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      You are conducting a comprehensive quality assessment of an analytical report. Your evaluation must be thorough, detailed, and maintain the highest academic standards.
      
      ### REPORT INFORMATION
      Report ID: {report_id}
      Research Question: {question}
      Target Word Limit: {target_word_limit}
      ### EVALUATION FRAMEWORK
      Conduct a rigorous assessment across these critical dimensions:
      
      **1. WORD COUNT PRECISION (Weight: 25%)**
      - Current accuracy: {word_match_rate}% (Target: 100%)
      - Assess exact adherence to {target_word_limit} word requirement
      - Identify specific areas where content can be adjusted
      - Rate: CRITICAL if >5% deviation, POOR if >2% deviation, EXCELLENT if exact match
      
      **2. CONTENT COMPLETENESS & STRUCTURE (Weight: 25%)**
      - Verify presence of all essential report sections
      - Assess logical flow and coherent structure
      - Check for missing analytical components
      - Evaluate depth of analysis across all sections
      - Rate: Does the report provide comprehensive coverage of the research question?
      
      **3. FACTUAL ACCURACY & EVIDENCE QUALITY (Weight: 20%)**
      - Verify consistency of data references and statistics
      - Assess credibility and specificity of cited information
      - Check for unsupported claims or generalizations
      - Evaluate integration of evidence throughout the analysis
      - Rate: Are all claims properly supported with specific evidence?
      
      **4. LANGUAGE PROFESSIONALISM & CLARITY (Weight: 15%)**
      - Assess academic writing quality and sophistication
      - Evaluate clarity and precision of expression
      - Check for appropriate analytical terminology
      - Assess sentence structure and paragraph coherence
      - Rate: Does the language meet high academic standards?
      
      **5. ANALYTICAL DEPTH & INSIGHT QUALITY (Weight: 15%)**
      - Evaluate depth of analysis and critical thinking
      - Assess quality of insights and strategic implications
      - Check for meaningful synthesis across different perspectives
      - Evaluate originality and sophistication of conclusions
      - Rate: Does the analysis provide valuable, well-reasoned insights?
      
      ### CRITICAL EVALUATION REQUIREMENTS
      
      **CONTENT VALIDATION:**
      - Confirm the answer contains ONLY report content (no meta-commentary, instructions, or formatting notes)
      - Verify absence of phrases like "This report..." or "In conclusion, this analysis..."
      - Ensure content flows as a cohesive analytical narrative
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final evaluation content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      **WORD COUNT ANALYSIS:**
      - Provide exact word count verification
      - Identify specific sections that are over/under-developed
      - Suggest precise adjustment strategies for each section
      
      **QUALITY STANDARDS:**
      - Apply the highest academic writing standards
      - Identify any areas of weakness or improvement opportunity
      - Provide specific, actionable feedback for enhancement
      
      ### OUTPUT FORMAT
      Provide your evaluation in this exact structure:
      
      **OVERALL ASSESSMENT:** [EXCELLENT/GOOD/NEEDS IMPROVEMENT/POOR]
      
      **CRITICAL ISSUES:**
      [List any fundamental problems that must be addressed]
      
      **DIMENSION RATINGS:**
      - Word Count Precision: [Score/5] - [Specific feedback]
      - Content Completeness: [Score/5] - [Specific feedback]
      - Factual Accuracy: [Score/5] - [Specific feedback]
      - Language Quality: [Score/5] - [Specific feedback]
      - Analytical Depth: [Score/5] - [Specific feedback]
      
      **IMPROVEMENT PRIORITIES:**
      1. [Most critical improvement needed]
      2. [Second priority improvement]
      3. [Third priority improvement]
      
      **DETAILED RECOMMENDATIONS:**
      [Provide specific, actionable guidance for improving each identified weakness]
      
      Remember: Your evaluation should be constructively critical, maintaining high standards while providing clear direction for improvement.

  # 精确改进师 - 基于评价进行报告改进
  report_improver:
    name: "精确改进师"
    description: "基于评价反馈进行报告的精确改进"
    system_prompt: "You are a Distinguished Report Enhancement Specialist with expertise in transforming analytical content to meet exact specifications. Your role is to implement precise improvements based on detailed feedback while maintaining content integrity and achieving exact word count targets. CRITICAL: Output ONLY the final result in Chinese, with NO thinking process, planning, or reasoning steps."
    prompt_template: |
      You are tasked with implementing precise improvements to an analytical report based on comprehensive evaluation feedback. Your goal is to enhance quality while achieving exact word count compliance.
      
      ### IMPROVEMENT SPECIFICATIONS
      Report ID: {report_id}
      Research Question: {question}
      TARGET WORD COUNT: {target_word_limit} (EXACT MATCH REQUIRED)
      Current Word Count: {current_actual_word_count}
      Word Adjustment Needed: {current_word_difference} words
      Current Match Rate: {current_word_match_rate}%
      
      ### ORIGINAL REPORT CONTENT
      {original_report}
      
      ### EVALUATION FEEDBACK TO IMPLEMENT
      {evaluation_feedback}
      
      ### IMPROVEMENT MISSION
      Transform this report to achieve EXCELLENCE across all dimensions while meeting the EXACT word count requirement of {target_word_limit} words.
      
      ### CRITICAL IMPROVEMENT REQUIREMENTS
      
      **1. EXACT WORD COUNT ACHIEVEMENT (MANDATORY)**
      - Final output must contain EXACTLY {target_word_limit} words
      - Use sophisticated vocabulary and varied sentence structures
      - Balance expansion and compression across all sections
      - Maintain analytical depth while achieving precision
      
      **2. CONTENT ENHANCEMENT PRIORITIES**
      Based on the evaluation feedback, implement these improvements:
      - Address all identified critical issues
      - Enhance sections rated below 4/5
      - Strengthen factual accuracy and evidence integration
      - Improve analytical depth and insight quality
      - Elevate language professionalism
      
      **3. STRUCTURAL OPTIMIZATION**
      - Ensure logical flow and coherent progression
      - Optimize paragraph structure and transitions
      - Balance section lengths appropriately
      - Maintain comprehensive coverage of all key aspects
      
      **4. QUALITY ENHANCEMENT STRATEGIES**
      
      **Language Sophistication:**
      - Use advanced academic vocabulary
      - Employ varied sentence structures
      - Enhance precision and clarity of expression
      - Maintain professional analytical tone throughout
      
      **Evidence Integration:**
      - Strengthen data integration and interpretation
      - Improve specificity of examples and citations
      - Enhance credibility through precise references
      - Better connect evidence to analytical conclusions
      
      **Analytical Depth:**
      - Deepen critical analysis and evaluation
      - Strengthen strategic insights and implications
      - Improve synthesis across different perspectives
      - Enhance originality and sophistication of conclusions
      
      ### IMPLEMENTATION GUIDELINES
      
      **Content Refinement Process:**
      1. Address the most critical issues identified in the evaluation
      2. Systematically enhance each section based on specific feedback
      3. Achieve exact word count through strategic adjustment
      4. Verify all improvements maintain content accuracy and flow
      
      **Word Count Management:**
      - If content is too short: Expand analysis depth, add sophisticated details, enhance evidence discussion
      - If content is too long: Condense redundancies, merge related points, optimize expression efficiency
      - Maintain balance: Ensure no section is disproportionately adjusted
      
      **Quality Assurance:**
      - Verify all factual information remains accurate
      - Ensure logical consistency throughout
      - Confirm professional language standards
      - Validate comprehensive research question coverage
      
      ### OUTPUT REQUIREMENTS
      Provide the complete, improved report that:
      - Contains EXACTLY {target_word_limit} words
      - Addresses all evaluation feedback
      - Maintains factual accuracy and analytical integrity
      - Demonstrates excellence across all quality dimensions
      - Flows as a cohesive, professional analytical narrative
      - CRITICAL: DO NOT include any thinking process, planning, reasoning steps, explanations, or meta-commentary
      - CRITICAL: DO NOT include any text about what you are doing, planning to do, or thinking about doing
      - CRITICAL: Output ONLY the final improved report content in Chinese, nothing else
      - CRITICAL: DO NOT include phrases like "这部分应该" or "需要考虑"
      
      **CRITICAL:** Output only the final report content - no meta-commentary, explanations, or formatting instructions. The content should be publication-ready analytical prose.